name: Atomic-Void-Devcontainer
networks:
  kafka:
    name: kafka
    driver: bridge
  ollama:
    name: ollama
    driver: bridge
services:
  app:
    image: ${DOCKER_IMAGE}
    container_name: app
    networks:
      - kafka
      - ollama
    volumes:
      - ..:/workspaces:cached
    command: sleep infinity
